services:
  database:
    image: postgres:18.3
    shm_size: 512mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres_final:/var/lib/postgresql/data 
    
  project:
    image: "ferroscope-test"
    environment:
      CORS: "http://localhost:3000,http://127.0.0.1:3000"
      PSQL_URL: postgres://myuser:mypassword@database:5432/mydatabase
      EMAIL_HOST: 
      EMAIL_HOST_USER: 
      EMAIL_HOST_PASSWORD: 
      DEVMAIL: 
    user: "scope:scope"
    ports:
      - "8000:8000"