mod read;
mod urls;
mod auth;
mod write;
mod payloads;
mod response;
pub mod types;
mod streaming;
mod user_management;
pub use urls::base_routers;
use crate::middleware::user_auth as middleware;
pub use response::{LatestCpu, LatestRam,NodeDiskIoStats};